max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
where_single_line = true
format_code_in_doc_comments = true
wrap_comments = true